name: solar system workflow

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'   
env:
  MONGO_URI: 'mongodb+srv://superuser:superpassword@cluster0.ppefvpi.mongodb.net/superData'            
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
    unit-testing:
        name: unit-test
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo code
              uses: actions/checkout@v4

            - name: setup node verison 18
              uses: actions/setup-node@v5
              with:
                node-version: 18

            - name: install-dependency 
              run: npm install


    code-coverage:
      needs: unit-testing
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo code
          uses: actions/checkout@v4
          
        - name: setup node version 18
          uses: actions/setup-node@v5
          with:
            node-version: 18

        - name: install dependency 
          run: npm install

        - name: code coverage test
          run: npm run coverage

        - name: archive test result
          uses: actions/upload-artifact@v5
          with:
            name: code coverage result 
            path: coverage
            retention-days: 5  # insted of delete file manully , with this feature file will deleted after 5 days automaticlly 
          
      
